version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies with npm...
      - npm install
  build:
    commands:
      - npm test
      - npm run build
artifacts:
  files:
    - '**/*' 
cache:
  paths:
    - node_modules
