version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies with npm...
      - npm install
  build:
    commands:
      - npm test
      - npm run build
artifacts:
  files:
    - 'index.html'
  # - **/*
  # discard-paths: no
  # base-directory: dist    
cache:
  paths:
    - node_modules
